project_name: "whosthere"
version: 2

before:
  hooks:
    - go mod tidy
    - go generate

builds:
  - main: ./main.go
    binary: whosthere
    goos: ["linux"]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w -X main.versionStr={{.Version}}
      - -X main.commitStr={{ .Commit }}
      - -X main.dateStr={{ .Date }}
    env:
      # The CGO_ENABLED=1 is required for clipboard support
      # see https://github.com/golang-design/clipboard
      - CGO_ENABLED=1
    overrides:
      - goos: linux
        goarch: "arm64"
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: "386"
        env:
          - CC=i686-linux-gnu-gcc
      - goos: linux
        goarch: "amd64"
        env:
          - CC=gcc
